namespace-regex = '^admin\.(forum_messages|forum_topics|forum_faq_articles|forum_news)$'

direct-read-namespaces = ["admin.forum_topics", "admin.forum_messages", "admin.forum_faq_articles", "admin.forum_news"]

mapper-plugin-path="./myplugin.so"

change-stream-namespaces=["admin"]
